# Generated by Django 4.2.7 on 2023-11-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(choices=[(1, 'best'), (2, 'medium'), (3, 'worst')]),
        ),
    ]
